name: Deploy Dashboard Miranda

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20.9.0
      uses: actions/setup-node@v4
      with:
          node-version: v20.9.0
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
      env: 
          VITE_API_BASE: ${{secrets.VITE_API_BASE}}
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_VITE_API_BASE: ${{secrets.VITE_API_BASE}}
        directory: './'
        file_name: .env
        fail_on_empty: true
        sort_keys: false
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev-test
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-3' # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'
