name: Deploy Dashboard Miranda

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20.9.0
      uses: actions/setup-node@v4
      with:
          node-version: v20.9.0
    - name: Install Dependencies
      run: npm ci
    - name: Build Project
      run: npm run build
    - uses: actions/checkout@master
      run: ls -a
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-3' # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'